sudo: false
language: node_js
node_js:
    - "10"
#services:
#    - mongodb
deploy:
  provider: azure_web_apps
  username: "sudoku-service\$sudoku-service"
  site: "sudoku-service"
  verbose: true
cache:
    directories:
        - node_modules
script:
    - npm run build
    - npm run test
